/home/luc/hgwork/lino/docs/api/lino.management.commands.makescreenshots.rst:4: WARNING: autodoc: failed to import module u'lino.management.commands.makescreenshots'; the following exception was raised:
Traceback (most recent call last):
  File "/home/luc/pythonenvs/py27/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "/home/luc/hgwork/lino/lino/management/commands/makescreenshots.py", line 39, in <module>
    from django.core.servers.basehttp import WSGIServerException, get_internal_wsgi_application
ImportError: cannot import name WSGIServerException
/home/luc/hgwork/lino/docs/api/lino.management.commands.syncscreenshots.rst:4: WARNING: autodoc: failed to import module u'lino.management.commands.syncscreenshots'; the following exception was raised:
Traceback (most recent call last):
  File "/home/luc/pythonenvs/py27/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "/home/luc/hgwork/lino/lino/management/commands/syncscreenshots.py", line 48, in <module>
    from django.core.servers.basehttp import WSGIServerException, get_internal_wsgi_application
ImportError: cannot import name WSGIServerException
