/home/luc/hgwork/lino/docs/_api/_mixins/lino.mixins.babel.rst:4: WARNING: autodoc: failed to import module u'lino.mixins.babel'; the following exception was raised:
Traceback (most recent call last):
  File "/home/luc/repositories/sphinx/sphinx/ext/autodoc.py", line 367, in import_object
    __import__(self.modname)
ImportError: No module named babel
/home/luc/hgwork/lino/docs/_api/_mixins/lino.mixins.babel.rst:: WARNING: document isn't included in any toctree
